#!/usr/bin/bash -e

# settings
name=$(hostname)
osName=$(/usr/bin/cat /etc/os-release | /usr/bin/egrep -i 'pretty_name' | /usr/bin/awk -F'\"' '{print $2}')
logDIR=/home/pi/log
logfn=$logDIR/${name}-update-os.log
if [[ ! -d $logDIR ]]; then mkdir $logDIR; chown pi:pi $logDIR; fi 

# timestamp function
timestamp()
{
    date +%F_%T
}

# main body
echo "$(timestamp) ***" >> $logfn
echo "$(timestamp) *** upgrade ${osName} on ${name^}" >> $logfn
echo "$(timestamp) ***" >> $logfn
/usr/bin/apt-get upgrade -y >> $logfn
if [[ $? = 0 ]]; then
    echo "$(timestamp) ***" >> $logfn
    echo "$(timestamp) *** upgrade successfully completed!" >> $logfn
    echo "$(timestamp) ***" >> $logfn
    echo -e "\n\n" >> $logfn
else
    echo "$(timestamp) ***" >> $logfn
    echo "$(timestamp) *** ERROR occured during upgrade, please check!" >> $logfn
    echo "$(timestamp) ***" >> $logfn
    echo -e "\n\n" >> $logfn
    exit 5
fi

# cleaning up and freeing up memory cache
/usr/bin/apt-get clean
/usr/bin/sync; echo 1 > /proc/sys/vm/drop_caches

# restart rpi-monitor.service daemon
/usr/bin/systemctl restart rpi-monitor.service >> $logfn
